### ISSUE TITLE
Extra outputs

### ISSUE THREAD

**Issue by dbrekelmans** [bruceadams/get-release#11]
The [Github API](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name) provides a lot more output information than this action does.

I'm interested in using the following extra outputs:

- name
- body
- draft
- prerelease

BTW, nice simple action. I like it ;)

**Comment by bruceadams** [comment]
Thanks! Adding those outputs looks easy. I'll get around to adding them in a day or two. Your are more than welcome to submit a pull request adding them.

**Comment by dbrekelmans** [comment]
Done in #12 👍

**Comment by bruceadams** [comment]
Awesome! Merged! I'll cut a new point release in a moment (once I remember how to do that in this repo 😊).

**Comment by bruceadams** [comment]
Released at v1.2.2 🎉
