### ISSUE TITLE
Error 404 when fetching the release

### ISSUE THREAD

**Issue by lyrixx** [bruceadams/get-release#30]
see: https://github.com/jolicode/castor/actions/runs/5879009613/job/15946039587

Indeed, the GitHub API seems to not work anymore! 

```
https://api.github.com/repos/jolicode/castor/releases/tags/
```

**Comment by bruceadams** [comment]
Huh. The [get-release code attempts to get the tag name from the GitHub Actions context](https://github.com/bruceadams/get-release/blob/main/src/get-release.js#L17) and appears to have not gotten anything. Adding the appropriate tag name onto the URL, https://api.github.com/repos/jolicode/castor/releases/tags/v0.8.0, works as expected. I don't have any initial theories about what went wrong.

**Comment by lyrixx** [comment]
We now use gh CLI binary so it's not a problem for us anymore. Feel free to close the issue 👍🏼
