### ISSUE TITLE
Example from README.md doesn't work

### ISSUE THREAD

**Issue by ggbecker** [bruceadams/get-release#5]
using `bruceadams/get-release@v1` doesn't work

It needs to use `bruceadams/get-release@v1.2.0`

**Comment by bruceadams** [comment]
Oh, my. Yes. The README needs a bit work. Thanks for the nudge. I may not get to it until tomorrow.

**Comment by jossef** [comment]
ping

**Comment by SylvainAON3D** [comment]
@bruceadams I made the modification as described by @ggbecker but now I am having this error:

![image](https://user-images.githubusercontent.com/46899425/88837049-af5ae480-d1a5-11ea-9f68-ede98be9ca03.png)

The code is:

```
      - name: "Checkout the code"
        uses: actions/checkout@v2

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
```

So probably miss a little more information on README.md, might be basic but I am new to Github actions...

**Comment by ggbecker** [comment]
@SylvainAON3D I'm using that here: https://github.com/ggbecker/morning-library-uploader/blob/master/.github/workflows/build.yml#L93 check it out, it might help

**Comment by SylvainAON3D** [comment]
@ggbecker Yes it did work for me, thanks. So need to add:

```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by bruceadams** [comment]
Thanks @ggbecker for helping! ❤️ I'm sorry for being slow making updates here.

**Comment by bruceadams** [comment]
I updated the README, finally. I _think_ it's a lot better. I'm very happy to hear comments! (And I'll try to be more responsive!)
